# These are some default pre-commit hooks recommended for splunk packages.
# run ``pre-commit install`` & then ``pre-commit run --all-files`` to check.

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-executables-have-shebangs # Ensures that (non-binary) executable files have a shebang.
      - id: check-merge-conflict # Check for files that contain merge conflict strings.
      - id: check-toml # This hook checks toml files for parseable syntax.
      - id: check-xml # This hook checks xml files for parseable syntax.
      - id: check-yaml # This hook checks yaml files for parseable syntax.
      - id: detect-private-key # Detects the presence of private keys
      - id: end-of-file-fixer # Ensures that a file is either empty, or ends with one newline.
      - id: trailing-whitespace # This hook trims trailing whitespace.

  - repo: https://github.com/Lucas-C/pre-commit-hooks-java
    rev: 1.3.8
    hooks:
    -   id: validate-html # HTML syntax validator using W3C v.Nu checker, with support for handlebars/jinja2 templates
        args: [--remove-mustaches, "--ignore=Expected \"<!DOCTYPE html>\""]
        # files: ^src/main/html/
