# Author: Michael Bischof <michael@nextpart.io>
# Organisation: Nextpart Security Intelligence GmbH
name: $(Date:yyyyMMdd)$(Rev:.r)

pool: Native

variables:
  - group: docker # Variables in Pipelines/Library
  - group: splunk-package
  - name: APP_DIR # Used by packaging image to locate apps
    value: $(Pipeline.Workspace)/s/apps
  - name: PKG_DIR # Used by packaging image to store results
    value: $(Build.ArtifactStagingDirectory)/package

trigger:
  branches:
    include: ["*"]

resources:
  repositories:
    - repository: templates
      type: git
      name: Splunksters/Pipelines

stages:
  - stage: PackageValidation
    pool: Native
    jobs:
      #
      - template: splunk_app.azure-pipelines.yml@templates
